//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDAWebPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission
    {
        public int Id { get; set; }
        public int SessionId { get; set; }
        public int CredentialId { get; set; }
        public string AdmissionId { get; set; }
        public string AccessPin { get; set; }
        public System.DateTime DateAdmissionRequested { get; set; }
        public System.DateTime DatePinApplied { get; set; }
        public int AdmissionStatus { get; set; }
        public bool IsDeleted { get; set; }
    }
}
