//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDAWebPortal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NDAPortalDatabaseEntities : DbContext
    {
        public NDAPortalDatabaseEntities()
            : base("name=NDAPortalDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admission> Admissions { get; set; }
        public virtual DbSet<Credential> Credentials { get; set; }
        public virtual DbSet<CredentialArea> CredentialAreas { get; set; }
        public virtual DbSet<PinMap> PinMaps { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<UploadedParticular> UploadedParticulars { get; set; }
        public virtual DbSet<Programme> Programmes { get; set; }
        public virtual DbSet<SubProgramme> SubProgrammes { get; set; }
        public virtual DbSet<Locality> Localities { get; set; }
        public virtual DbSet<State> States { get; set; }
    
        public virtual int InitializeStateLga()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InitializeStateLga");
        }
    }
}
