//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDAWebPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PinMap
    {
        public int Id { get; set; }
        public int CredentialId { get; set; }
        public string PinData { get; set; }
        public int PinUse { get; set; }
        public bool CanExpire { get; set; }
        public Nullable<System.DateTime> InitiationDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public int CredentialAssigned { get; set; }
        public bool HasUseCounts { get; set; }
        public Nullable<int> UseCount { get; set; }
        public Nullable<int> UseCountMax { get; set; }
        public bool IsDeleted { get; set; }
    }
}
