//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDAWebPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubProgramme
    {
        public int Id { get; set; }
        public int ProgrammeId { get; set; }
        public string SubProgrammeCode { get; set; }
        public string SubProgrammeName { get; set; }
        public bool IsDeleted { get; set; }
    }
}
