//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDAWebPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadedParticular
    {
        public long Id { get; set; }
        public string AdmissionId { get; set; }
        public string RegistationGuid { get; set; }
        public int ActiveSessionId { get; set; }
        public int CredentialId { get; set; }
        public int DocumentTypeId { get; set; }
        public string FileNameData { get; set; }
        public bool IsDeleted { get; set; }
    }
}
