CREATE TABLE [dbo].[Registration] (
    [Id]                       BIGINT        IDENTITY (1, 1) NOT NULL,
    [RegistrationGuid]         VARCHAR (100) NOT NULL,
    [AdmissionId]              VARCHAR (100) NOT NULL,
    [CredentialId]             INT           NOT NULL,
    [SessionId]                INT           NOT NULL,
    [Surname]                  VARCHAR (100) NULL,
    [FirstName]                VARCHAR (100) NULL,
    [OtherName]                VARCHAR (100) NULL,
    [DateOfBirth]              DATETIME      NULL,
    [Sex]                      VARCHAR (10)  NULL,
    [Religion]                 VARCHAR (100) NULL,
    [MaritalStatus]            VARCHAR (100) NULL,
    [PhysicalFeatures]         VARCHAR (100) NULL,
    [Nationality]              VARCHAR (100) NULL,
    [HomeAddress]              VARCHAR (100) NULL,
    [StateOfOrigin]            VARCHAR (100) NULL,
    [LgaOfOrigin]              VARCHAR (100) NULL,
    [HomeTown]                 VARCHAR (100) NULL,
    [LandMarks]                VARCHAR (100) NULL,
    [BloodType]                VARCHAR (100) NULL,
    [Genotype]                 VARCHAR (100) NULL,
    [Hobbies]                  VARCHAR (100) NULL,
    [ForceFullName]            VARCHAR (100) NULL,
    [ForceRelationship]        VARCHAR (100) NULL,
    [ForceUnit]                VARCHAR (100) NULL,
    [SponsorFullName]          VARCHAR (100) NULL,
    [SponsorRelationship]      VARCHAR (100) NULL,
    [SponsorEmail]             VARCHAR (100) NULL,
    [SponsorPhoneNumber]       VARCHAR (100) NULL,
    [SponsorYearlyIncome]      BIGINT        NULL,
    [NokFullName]              VARCHAR (100) NULL,
    [NokRelationship]          VARCHAR (100) NULL,
    [NokEmail]                 VARCHAR (100) NULL,
    [NokPhoneNumber]           VARCHAR (100) NULL,
    [PgFullName]               VARCHAR (100) NULL,
    [PgRelationship]           VARCHAR (100) NULL,
    [PgEmail]                  VARCHAR (100) NULL,
    [PgPhoneNumber]            VARCHAR (100) NULL,
    [FirstChoiceProgramme]     INT           NULL,
    [FirstChoiceSubProgramme]  INT           NULL,
    [SecondChoiceProgramme]    INT           NULL,
    [SecondChoiceSubProgramme] INT           NULL,
    [IsDeleted]                BIT           NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);



